#!/usr/bin/env python

# This file is a part of Jing.
#
# Copyright (c) 2015 The Jing Authors.
#
# For the full copyright and license information, please view the LICENSE file
# that was distributed with this source code.

import sys
from subprocess import Popen, PIPE

if len(sys.argv) < 3:
    print "usage: pass_test <program> <file...>"
    sys.exit(1)

program = sys.argv[1]
test_files = sys.argv[2:]
passed = 0
failed = 0

def get_expected_output(test_file):
    begin = False
    expected_str = ""
    with open(test_file, 'rb') as f:
        for i, line in enumerate(f.readlines()):
            if not begin:
                idx = line.find("// EXPECTED OUTPUT")
                if idx >= 0:
                    begin = True
            else:
                idx = line.find("// ")
                if idx >= 0:
                    expected_str += line[idx+3:]
                else:
                    break
    return expected_str

for f in test_files:
    expected_output = get_expected_output(f)
    cmd = [program, f]
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)
    stdout, stderr = p.communicate()
    if expected_output == stdout and stderr == '' and 0 == p.returncode:
        passed += 1
        print "ok: %s passed" % f
    else:
        failed += 1
        print "error: %s failed with exit code %d" % (f, p.returncode)
        if len(stderr):
            print "stderr:"
            print stderr
            print ""
        print "expected:"
        print expected_output
        print "actual:"
        print stdout

if failed:
    print "\033[31m"
else:
    print "\033[32m"
print "Tests: %d, Passed: %d, Failed: %d" % (len(test_files), passed, failed)
print "\033[0m"
