#!/usr/bin/env python

# This file is a part of Jing.
#
# Copyright (c) 2015 The Jing Authors.
#
# For the full copyright and license information, please view the LICENSE file
# that was distributed with this source code.

import sys
from subprocess import Popen, PIPE

if len(sys.argv) < 3:
    print "usage: tvalgrind <program> <file...>"
    sys.exit(1)

program = sys.argv[1]
test_files = sys.argv[2:]
passed = 0
failed = 0

def leak_check_pass(output):
    return output.find("in use at exit: 0 bytes in 0 blocks") >= 0

for f in test_files:
    cmd = ["valgrind", program, f]
    p = Popen(cmd, stdout=PIPE, stderr=PIPE)
    stdout, stderr = p.communicate()
    if leak_check_pass(stderr):
        passed += 1
        print "ok: %s passed" % f
    elif 0 != p.returncode:
        failed += 1
        print "error: %s valgrind exited with status %d" % (f, p.returncode)
    else:
        failed += 1
        print "error: %s failed with exit code %d" % (f, p.returncode)
        if len(stderr):
            print "stderr:"
            print stderr
        if len(stdout):
            print "stdout:"
            print stdout

if failed:
    print "\033[31;1m"
else:
    print "\033[32;1m"
print "Tests: %d, Passed: %d, Failed: %d" % (len(test_files), passed, failed)
print "\033[m"
